"""Application-layer composition for authoritative cross-module workflows."""

from .candidate_insight import (
    CANDIDATE_INSIGHT_TASK_TYPE,
    CandidateInsightEvidence,
    CandidateInsightKind,
    CandidateInsightOutput,
    CandidateInsightPersister,
)
from .candidate_insight_command import (
    CandidateInsightGenerationResult,
    CandidateInsightGenerationStatus,
    CandidateInsightRuntime,
    GenerateCandidateInsight,
)
from .candidate_insight_safety import CandidateInsightMemorySafetyClassifier
from .memory_evidence import (
    AsyncMemoryEvidenceExcerptService,
    MemoryEvidenceExcerpt,
    MemoryEvidenceExcerptResolver,
)
from .model_gateway import (
    GovernedModelGateway,
    KnowledgeAuthorizationSnapshotAdapter,
    KnowledgeEvidenceAuthorityAdapter,
    ModelTaskDefinition,
    PreparedModelInvocation,
    SourceAuthoritySnapshot,
    SourceConsentAuthority,
    SourceFragmentPlaintextReader,
)
from .model_runtime import (
    GovernedModelRuntime,
    ModelResultContext,
    ModelResultPersister,
    ModelResultRejected,
    ModelRunDispatchConflict,
    ModelRunFinalizationConflict,
    ModelRunFingerprintFactory,
    ModelRunProviderOutcomeUnknown,
    ModelRunProviderUnavailable,
    ModelRunReplayArtifactMissing,
    ModelRunReplayInProgress,
    ModelRunReplayTerminal,
    ModelRunResultDiscarded,
    ModelRunResultPersistenceError,
    ModelRuntimeError,
    ModelRunTimeout,
)
from .source_entries import (
    AppendEntryRevisionCommand,
    CreateEntryCommand,
    LocalAesGcmSourceContentProtector,
    PostgresSourceEntryService,
    ProtectedCorrectionSourceRecorder,
    ProtectedSourceFragmentPlaintextReader,
    SourceContentProtector,
    SourceContentUnavailable,
    SourceCursorCodec,
    SourceEntryService,
)

__all__ = [
    "CANDIDATE_INSIGHT_TASK_TYPE",
    "AppendEntryRevisionCommand",
    "AsyncMemoryEvidenceExcerptService",
    "CandidateInsightEvidence",
    "CandidateInsightGenerationResult",
    "CandidateInsightGenerationStatus",
    "CandidateInsightKind",
    "CandidateInsightMemorySafetyClassifier",
    "CandidateInsightOutput",
    "CandidateInsightPersister",
    "CandidateInsightRuntime",
    "CreateEntryCommand",
    "GenerateCandidateInsight",
    "GovernedModelGateway",
    "GovernedModelRuntime",
    "KnowledgeAuthorizationSnapshotAdapter",
    "KnowledgeEvidenceAuthorityAdapter",
    "LocalAesGcmSourceContentProtector",
    "MemoryEvidenceExcerpt",
    "MemoryEvidenceExcerptResolver",
    "ModelResultContext",
    "ModelResultPersister",
    "ModelResultRejected",
    "ModelRunDispatchConflict",
    "ModelRunFinalizationConflict",
    "ModelRunFingerprintFactory",
    "ModelRunProviderOutcomeUnknown",
    "ModelRunProviderUnavailable",
    "ModelRunReplayArtifactMissing",
    "ModelRunReplayInProgress",
    "ModelRunReplayTerminal",
    "ModelRunResultDiscarded",
    "ModelRunResultPersistenceError",
    "ModelRunTimeout",
    "ModelRuntimeError",
    "ModelTaskDefinition",
    "PostgresSourceEntryService",
    "PreparedModelInvocation",
    "ProtectedCorrectionSourceRecorder",
    "ProtectedSourceFragmentPlaintextReader",
    "SourceAuthoritySnapshot",
    "SourceConsentAuthority",
    "SourceContentProtector",
    "SourceContentUnavailable",
    "SourceCursorCodec",
    "SourceEntryService",
    "SourceFragmentPlaintextReader",
]
