"""Application-layer composition for authoritative cross-module workflows."""

from .candidate_insight import (
    CANDIDATE_INSIGHT_TASK_TYPE,
    CandidateInsightEvidence,
    CandidateInsightKind,
    CandidateInsightOutput,
    CandidateInsightPersister,
)
from .model_gateway import (
    GovernedModelGateway,
    KnowledgeAuthorizationSnapshotAdapter,
    KnowledgeEvidenceAuthorityAdapter,
    ModelTaskDefinition,
    PreparedModelInvocation,
    SourceAuthoritySnapshot,
    SourceConsentAuthority,
    SourceFragmentPlaintextReader,
)
from .model_runtime import (
    GovernedModelRuntime,
    ModelResultContext,
    ModelResultPersister,
    ModelResultRejected,
    ModelRunDispatchConflict,
    ModelRunFinalizationConflict,
    ModelRunFingerprintFactory,
    ModelRunProviderOutcomeUnknown,
    ModelRunResultDiscarded,
    ModelRunResultPersistenceError,
    ModelRuntimeError,
    ModelRunTimeout,
)
from .source_entries import (
    AppendEntryRevisionCommand,
    CreateEntryCommand,
    LocalAesGcmSourceContentProtector,
    PostgresSourceEntryService,
    ProtectedCorrectionSourceRecorder,
    ProtectedSourceFragmentPlaintextReader,
    SourceContentProtector,
    SourceContentUnavailable,
    SourceCursorCodec,
    SourceEntryService,
)

__all__ = [
    "CANDIDATE_INSIGHT_TASK_TYPE",
    "AppendEntryRevisionCommand",
    "CandidateInsightEvidence",
    "CandidateInsightKind",
    "CandidateInsightOutput",
    "CandidateInsightPersister",
    "CreateEntryCommand",
    "GovernedModelGateway",
    "GovernedModelRuntime",
    "KnowledgeAuthorizationSnapshotAdapter",
    "KnowledgeEvidenceAuthorityAdapter",
    "LocalAesGcmSourceContentProtector",
    "ModelResultContext",
    "ModelResultPersister",
    "ModelResultRejected",
    "ModelRunDispatchConflict",
    "ModelRunFinalizationConflict",
    "ModelRunFingerprintFactory",
    "ModelRunProviderOutcomeUnknown",
    "ModelRunResultDiscarded",
    "ModelRunResultPersistenceError",
    "ModelRunTimeout",
    "ModelRuntimeError",
    "ModelTaskDefinition",
    "PostgresSourceEntryService",
    "PreparedModelInvocation",
    "ProtectedCorrectionSourceRecorder",
    "ProtectedSourceFragmentPlaintextReader",
    "SourceAuthoritySnapshot",
    "SourceConsentAuthority",
    "SourceContentProtector",
    "SourceContentUnavailable",
    "SourceCursorCodec",
    "SourceEntryService",
    "SourceFragmentPlaintextReader",
]
