"""initial governed schema

Revision ID: 302f9513f94b
Revises:
Create Date: 2026-08-24 01:49:42.282884
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from life_coach.modules.consent.provider_policy import ProviderPolicyType
from life_coach.modules.sources.object_reference import VaultObjectKeyType
from life_coach.platform.model_registry import load_model_registry
from life_coach.platform.postgres_security import apply_postgres_security
from life_coach.shared.database import Base

revision: str = "302f9513f94b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derived_object",
        sa.Column(
            "object_kind",
            sa.Enum(
                "claim_version",
                "insight_candidate",
                "narrative_claim",
                name="derived_object_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Enum(
                "knowledge_pipeline",
                "user",
                "source_reconciler",
                name="derived_object_created_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="knowledge_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "review_revision >= 0",
            name=op.f("ck_derived_object_derived_object_review_revision_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_derived_object")),
        sa.UniqueConstraint("vault_id", "id", name="uq_derived_object_vault_id_id"),
    )
    op.create_index(
        op.f("ix_derived_object_vault_id"), "derived_object", ["vault_id"], unique=False
    )
    op.create_table(
        "memory_claim",
        sa.Column(
            "kind",
            sa.Enum(
                "explicit_fact",
                "preference",
                "value",
                "goal",
                "relationship",
                "self_description",
                "pattern_hypothesis",
                name="memory_claim_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("subject_entity_id", sa.Uuid(), nullable=True),
        sa.Column("suppression_lineage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "knowledge_pipeline",
                "user",
                "source_reconciler",
                name="memory_claim_created_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="memory_claim_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_claim")),
        sa.UniqueConstraint("vault_id", "id", name="uq_memory_claim_vault_id_id"),
    )
    op.create_index(
        op.f("ix_memory_claim_suppression_lineage_id"),
        "memory_claim",
        ["suppression_lineage_id"],
        unique=False,
    )
    op.create_index(op.f("ix_memory_claim_vault_id"), "memory_claim", ["vault_id"], unique=False)
    op.create_table(
        "outbound_operation",
        sa.Column("connector", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("local_resource_version", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=79), nullable=False),
        sa.Column("provider_idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_generation", sa.Integer(), nullable=False),
        sa.Column("policy_epoch", sa.Integer(), nullable=False),
        sa.Column("source_generation", sa.Integer(), nullable=False),
        sa.Column("initial_tombstoned", sa.Boolean(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "executing",
                "unknown",
                "reconciling",
                "manual_review",
                "succeeded",
                "failed",
                "canceled",
                name="outboundoperationstate_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("max_reconciliation_attempts", sa.Integer(), nullable=False),
        sa.Column("execution_generation", sa.Integer(), nullable=False),
        sa.Column("execution_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciliation_generation", sa.Integer(), nullable=False),
        sa.Column("reconciliation_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciliation_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_class", sa.String(length=100), nullable=True),
        sa.Column("safe_error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "external_id IS NULL OR external_id ~ '^[A-Za-z0-9][A-Za-z0-9._~:/+=@-]{0,254}$'",
            name=op.f("ck_outbound_operation_outbound_external_id_provider_format"),
        ),
        sa.CheckConstraint(
            "length(request_hash) = 79 AND request_hash LIKE 'hmac-sha256:v1:%'",
            name=op.f("ck_outbound_operation_outbound_request_hash_vault_hmac"),
        ),
        sa.CheckConstraint(
            "local_resource_version ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z][a-z0-9_.-]{0,31}:([0-9]{1,20}|[0-9a-f]{16,64}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))$'",
            name=op.f("ck_outbound_operation_outbound_local_resource_version_technical"),
        ),
        sa.CheckConstraint(
            "local_resource_version ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'",
            name=op.f("ck_outbound_operation_outbound_local_resource_version_uuid"),
        ),
        sa.CheckConstraint(
            "provider_idempotency_key ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z][a-z0-9_.-]{0,31}:([0-9]{1,20}|[0-9a-f]{16,64}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))$'",
            name=op.f("ck_outbound_operation_outbound_provider_idempotency_key_technical"),
        ),
        sa.CheckConstraint(
            "request_hash ~ '^hmac-sha256:v1:[0-9a-f]{64}$'",
            name=op.f("ck_outbound_operation_outbound_request_hash_hex"),
        ),
        sa.CheckConstraint(
            "state != 'executing' OR execution_expires_at IS NOT NULL",
            name=op.f("ck_outbound_operation_outbound_executing_has_expiry"),
        ),
        sa.CheckConstraint(
            "state != 'reconciling' OR reconciliation_expires_at IS NOT NULL",
            name=op.f("ck_outbound_operation_outbound_reconciling_has_expiry"),
        ),
        sa.CheckConstraint(
            "state != 'succeeded' OR external_id IS NOT NULL",
            name=op.f("ck_outbound_operation_outbound_success_has_external_id"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_outbound_operation_outbound_attempts_nonnegative")
        ),
        sa.CheckConstraint(
            "authorization_generation >= 0",
            name=op.f("ck_outbound_operation_outbound_authorization_generation_nonnegative"),
        ),
        sa.CheckConstraint(
            "execution_generation >= 0",
            name=op.f("ck_outbound_operation_outbound_execution_generation_nonnegative"),
        ),
        sa.CheckConstraint(
            "initial_tombstoned = false",
            name=op.f("ck_outbound_operation_outbound_initial_source_not_tombstoned"),
        ),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_outbound_operation_outbound_max_attempts_positive")
        ),
        sa.CheckConstraint(
            "max_reconciliation_attempts >= 1",
            name=op.f("ck_outbound_operation_outbound_max_reconciliation_attempts_positive"),
        ),
        sa.CheckConstraint(
            "policy_epoch >= 0",
            name=op.f("ck_outbound_operation_outbound_policy_epoch_nonnegative"),
        ),
        sa.CheckConstraint(
            "reconciliation_generation >= 0",
            name=op.f("ck_outbound_operation_outbound_reconciliation_generation_nonnegative"),
        ),
        sa.CheckConstraint(
            "source_generation >= 0",
            name=op.f("ck_outbound_operation_outbound_source_generation_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_operation")),
        sa.UniqueConstraint(
            "vault_id",
            "authorization_id",
            "authorization_generation",
            name="uq_outbound_exact_authorization",
        ),
        sa.UniqueConstraint(
            "vault_id",
            "connector",
            "operation",
            "local_resource_version",
            name="uq_outbound_operation_scope",
        ),
        sa.UniqueConstraint(
            "vault_id",
            "connector",
            "provider_idempotency_key",
            name="uq_outbound_provider_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_outbound_operation_vault_id"), "outbound_operation", ["vault_id"], unique=False
    )
    op.create_table(
        "outbox_event",
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_revision_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=79), nullable=False),
        sa.Column(
            "payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "expected_job_types",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "idempotency_key ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z][a-z0-9_.-]{0,31}:([0-9]{1,20}|[0-9a-f]{16,64}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))$'",
            name=op.f("ck_outbox_event_outbox_event_idempotency_key_technical"),
        ),
        sa.CheckConstraint(
            "length(request_hash) = 79 AND request_hash LIKE 'hmac-sha256:v1:%'",
            name=op.f("ck_outbox_event_outbox_event_request_hash_vault_hmac"),
        ),
        sa.CheckConstraint(
            "request_hash ~ '^hmac-sha256:v1:[0-9a-f]{64}$'",
            name=op.f("ck_outbox_event_outbox_event_request_hash_hex"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
        sa.UniqueConstraint("id", "vault_id", name="uq_outbox_event_id_vault"),
        sa.UniqueConstraint(
            "vault_id",
            "event_type",
            "idempotency_key",
            name="uq_outbox_event_vault_type_idempotency",
        ),
    )
    op.create_index(op.f("ix_outbox_event_vault_id"), "outbox_event", ["vault_id"], unique=False)
    op.create_table(
        "vault",
        sa.Column("policy_epoch", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("source_generation", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("policy_epoch >= 0", name=op.f("ck_vault_policy_epoch_nonnegative")),
        sa.CheckConstraint(
            "source_generation >= 0", name=op.f("ck_vault_source_generation_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault")),
    )
    op.create_table(
        "claim_version",
        sa.Column("derived_object_id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("canonical_text", sa.Text(), nullable=False),
        sa.Column(
            "structured_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "epistemic_type",
            sa.Enum(
                "stated",
                "observed",
                "inferred",
                "user_authored",
                name="claim_epistemic_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "attribution",
            sa.Enum(
                "self_report",
                "quoted_other",
                "imported_record",
                "model_hypothesis",
                name="claim_attribution",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("uncertainty_text", sa.Text(), nullable=True),
        sa.Column(
            "initial_lifecycle_state",
            sa.Enum(
                "candidate",
                "active",
                "disputed",
                "superseded",
                "retracted",
                name="claim_initial_lifecycle_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "lifecycle_state",
            sa.Enum(
                "candidate",
                "active",
                "disputed",
                "superseded",
                "retracted",
                name="claim_lifecycle_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "valid_time_precision",
            sa.Enum(
                "exact",
                "day",
                "month",
                "year",
                "range",
                "unknown",
                name="claim_valid_time_precision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("valid_time_original", sa.Text(), nullable=True),
        sa.Column("valid_timezone", sa.String(length=128), nullable=True),
        sa.Column("system_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("system_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "confidence_band",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="claim_confidence_band",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("pipeline_version", sa.String(length=128), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin",
            sa.Enum(
                "pipeline_derived",
                "user_correction",
                name="claim_version_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "correction_mode",
            sa.Enum(
                "interpretation_error",
                "life_stage_change",
                name="claim_correction_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("supersedes_derived_object_id", sa.Uuid(), nullable=True),
        sa.Column("origin_verdict_id", sa.Uuid(), nullable=True),
        sa.Column("suppressed_by_derived_object_id", sa.Uuid(), nullable=True),
        sa.Column("suppression_override_verdict_id", sa.Uuid(), nullable=True),
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("authorization_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_policy_epoch", sa.Integer(), nullable=False),
        sa.Column("authorization_source_generation", sa.Integer(), nullable=False),
        sa.Column("safety_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("safety_allows_proactive", sa.Boolean(), nullable=False),
        sa.Column("subject_verification_id", sa.Uuid(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("vault_id"), "="),
            (sa.column("claim_id"), "="),
            (sa.text("tstzrange(system_from, system_to, '[)')"), "&&"),
            using="gist",
            name="excl_claim_version_system_overlap",
        ),
        sa.CheckConstraint(
            "authorization_policy_epoch >= 0 AND authorization_source_generation >= 0",
            name=op.f("ck_claim_version_claim_version_authorization_fence_nonnegative"),
        ),
        sa.CheckConstraint(
            "length(normalized_fingerprint) = 64",
            name=op.f("ck_claim_version_claim_version_fingerprint_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(pipeline_version) BETWEEN 1 AND 64",
            name=op.f("ck_claim_version_claim_version_pipeline_id_length"),
        ),
        sa.CheckConstraint(
            "system_to IS NULL OR system_from < system_to",
            name=op.f("ck_claim_version_claim_version_system_interval_nonempty"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from < valid_to",
            name=op.f("ck_claim_version_claim_version_valid_interval_nonempty"),
        ),
        sa.CheckConstraint(
            "version_no > 0", name=op.f("ck_claim_version_claim_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "claim_id"],
            ["memory_claim.vault_id", "memory_claim.id"],
            name="fk_claim_version_vault_memory_claim",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_claim_version_vault_derived_object",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "supersedes_derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_claim_version_vault_supersedes_derived",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "suppressed_by_derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_claim_version_vault_suppressed_by_derived",
        ),
        sa.PrimaryKeyConstraint("derived_object_id", name=op.f("pk_claim_version")),
        sa.UniqueConstraint(
            "vault_id", "claim_id", "version_no", name="uq_claim_version_vault_claim_version"
        ),
    )
    op.create_index(
        "ix_claim_version_bitemporal",
        "claim_version",
        ["vault_id", "claim_id", "valid_from", "valid_to", "system_from", "system_to"],
        unique=False,
    )
    op.create_index(op.f("ix_claim_version_claim_id"), "claim_version", ["claim_id"], unique=False)
    op.create_index(
        op.f("ix_claim_version_normalized_fingerprint"),
        "claim_version",
        ["normalized_fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_claim_version_vault_id"), "claim_version", ["vault_id"], unique=False)
    op.create_index(
        "uq_claim_version_current",
        "claim_version",
        ["vault_id", "claim_id"],
        unique=True,
        postgresql_where=sa.text("system_to IS NULL"),
        sqlite_where=sa.text("system_to IS NULL"),
    )
    op.create_table(
        "job",
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column(
            "queue",
            sa.Enum(
                "interactive",
                "ingest_text",
                "media",
                "reflection",
                "narrative",
                "privacy_critical",
                "integration",
                name="jobqueue_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_revision_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=79), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "waiting",
                "retrying",
                "done",
                "dead",
                "canceled",
                name="jobstate_values",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_generation", sa.Integer(), nullable=False),
        sa.Column("last_error_class", sa.String(length=100), nullable=True),
        sa.Column("safe_error_message", sa.String(length=500), nullable=True),
        sa.Column("consent_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("policy_epoch", sa.Integer(), nullable=False),
        sa.Column("source_generation", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(lease_owner IS NULL OR lease_owner ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z][a-z0-9_.-]{0,31}:([0-9]{1,20}|[0-9a-f]{16,64}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))$')",
            name=op.f("ck_job_job_lease_owner_technical"),
        ),
        sa.CheckConstraint(
            "idempotency_key ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z][a-z0-9_.-]{0,31}:([0-9]{1,20}|[0-9a-f]{16,64}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}))$'",
            name=op.f("ck_job_job_idempotency_key_technical"),
        ),
        sa.CheckConstraint(
            "length(request_hash) = 79 AND request_hash LIKE 'hmac-sha256:v1:%'",
            name=op.f("ck_job_job_request_hash_vault_hmac"),
        ),
        sa.CheckConstraint(
            "request_hash ~ '^hmac-sha256:v1:[0-9a-f]{64}$'",
            name=op.f("ck_job_job_request_hash_hex"),
        ),
        sa.CheckConstraint(
            "state != 'running' OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_job_job_running_has_lease"),
        ),
        sa.CheckConstraint(
            "state NOT IN ('done', 'dead', 'canceled') OR completed_at IS NOT NULL",
            name=op.f("ck_job_job_terminal_has_completion_time"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_job_job_attempts_nonnegative")),
        sa.CheckConstraint(
            "lease_generation >= 0", name=op.f("ck_job_job_lease_generation_nonnegative")
        ),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_job_job_max_attempts_positive")),
        sa.CheckConstraint("policy_epoch >= 0", name=op.f("ck_job_job_policy_epoch_nonnegative")),
        sa.CheckConstraint(
            "source_generation >= 0", name=op.f("ck_job_job_source_generation_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["outbox_event_id", "vault_id"],
            ["outbox_event.id", "outbox_event.vault_id"],
            name="fk_job_outbox_event_vault",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
        sa.UniqueConstraint(
            "vault_id", "job_type", "idempotency_key", name="uq_job_vault_type_idempotency"
        ),
        sa.UniqueConstraint(
            "vault_id",
            "job_type",
            "resource_revision_id",
            "pipeline_version",
            name="uq_job_vault_type_revision_pipeline",
        ),
    )
    op.create_index(
        "ix_job_claimable", "job", ["queue", "state", "run_after", "priority"], unique=False
    )
    op.create_index(op.f("ix_job_vault_id"), "job", ["vault_id"], unique=False)
    op.create_index(
        "uq_job_outbox_event_type",
        "job",
        ["outbox_event_id", "job_type"],
        unique=True,
        postgresql_where=sa.text("outbox_event_id IS NOT NULL"),
        sqlite_where=sa.text("outbox_event_id IS NOT NULL"),
    )
    op.create_table(
        "source_document",
        sa.Column(
            "source_type",
            sa.Enum(
                "note",
                "conversation",
                "audio",
                "image",
                "file",
                "import",
                name="source_type",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "first_party",
                "user_upload",
                "connector",
                name="source_origin",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("event_time_hint", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capture_timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "processing_state",
            sa.Enum(
                "ready",
                "pending",
                "partial",
                "failed",
                name="source_processing_state",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("retention_policy_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "data_class <> 'highly_sensitive' OR title IS NULL",
            name=op.f("ck_source_document_source_document_highly_sensitive_title_omitted"),
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "id", "current_revision_id"],
            ["source_revision.vault_id", "source_revision.document_id", "source_revision.id"],
            name="fk_source_document_current_revision_same_document",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vault.id"], name="fk_source_document_vault"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document")),
        sa.UniqueConstraint("vault_id", "id", name="uq_source_document_vault_id_id"),
    )
    op.create_index(
        op.f("ix_source_document_vault_id"), "source_document", ["vault_id"], unique=False
    )
    op.create_index(
        "ix_source_document_vault_live_created",
        "source_document",
        ["vault_id", "deleted_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "user_verdict",
        sa.Column("target_derived_object_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "confirm",
                "correct",
                "reject",
                "snooze",
                "retract",
                name="user_verdict_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("correction_text", sa.Text(), nullable=True),
        sa.Column(
            "replacement_payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("reason_optional", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "knowledge_pipeline",
                "user",
                "source_reconciler",
                name="verdict_created_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="verdict_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "verdict != 'correct' OR (correction_text IS NOT NULL AND length(trim(correction_text)) > 0 AND replacement_payload IS NOT NULL)",
            name=op.f("ck_user_verdict_user_verdict_correction_text_required"),
        ),
        sa.CheckConstraint(
            "verdict = 'correct' OR (correction_text IS NULL AND replacement_payload IS NULL)",
            name=op.f("ck_user_verdict_user_verdict_replacement_scoped"),
        ),
        sa.CheckConstraint(
            "sequence_no > 0", name=op.f("ck_user_verdict_user_verdict_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "target_derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_user_verdict_vault_derived_object",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_verdict")),
        sa.UniqueConstraint("vault_id", "id", name="uq_user_verdict_vault_id_id"),
        sa.UniqueConstraint(
            "vault_id",
            "target_derived_object_id",
            "sequence_no",
            name="uq_user_verdict_target_sequence",
        ),
    )
    op.create_index(
        "ix_user_verdict_stream",
        "user_verdict",
        ["vault_id", "target_derived_object_id", "sequence_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_verdict_target_derived_object_id"),
        "user_verdict",
        ["target_derived_object_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_verdict_vault_id"), "user_verdict", ["vault_id"], unique=False)
    op.create_table(
        "consent_record",
        sa.Column(
            "purpose",
            sa.Enum(
                "search",
                "passive_qa",
                "cross_record_analysis",
                "proactive_resurfacing",
                "narrative",
                "third_party_integration",
                "long_term_inference",
                name="consent_purpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum("grant", "revoke", name="consent_action", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum("vault", "source_document", name="consent_scope", native_enum=False, length=24),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_policy", ProviderPolicyType(), nullable=False),
        sa.Column("policy_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'vault' AND source_document_id IS NULL) OR (scope = 'source_document' AND source_document_id IS NOT NULL)",
            name=op.f("ck_consent_record_scope_matches_source_document"),
        ),
        sa.CheckConstraint(
            "created_by = 'user'", name=op.f("ck_consent_record_consent_actor_is_user")
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_consent_record_interaction_time_window_valid")
        ),
        sa.CheckConstraint(
            "length(trim(purpose)) > 0", name=op.f("ck_consent_record_purpose_nonempty")
        ),
        sa.CheckConstraint(
            "policy_epoch > 0", name=op.f("ck_consent_record_policy_epoch_positive")
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "source_document_id"],
            ["source_document.vault_id", "source_document.id"],
            name="fk_consent_record_vault_source_document",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id"], ["vault.id"], name="fk_consent_record_vault_id_vault"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_record")),
        sa.UniqueConstraint("vault_id", "id", name="uq_consent_record_vault_id_id"),
        sa.UniqueConstraint(
            "vault_id", "interaction_id", name="uq_consent_record_vault_id_interaction_id"
        ),
        sa.UniqueConstraint(
            "vault_id", "policy_epoch", name="uq_consent_record_vault_id_policy_epoch"
        ),
    )
    op.create_index(
        op.f("ix_consent_record_vault_id"), "consent_record", ["vault_id"], unique=False
    )
    op.create_index(
        "ix_consent_record_vault_purpose_source_epoch",
        "consent_record",
        ["vault_id", "purpose", "source_document_id", "policy_epoch"],
        unique=False,
    )
    op.create_table(
        "memory_suppression",
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("suppression_lineage_id", sa.Uuid(), nullable=False),
        sa.Column("source_derived_object_id", sa.Uuid(), nullable=False),
        sa.Column("source_verdict_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "confirm",
                "correct",
                "reject",
                "snooze",
                "retract",
                name="memory_suppression_verdict",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "knowledge_pipeline",
                "user",
                "source_reconciler",
                name="memory_suppression_created_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="memory_suppression_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(normalized_fingerprint) = 64",
            name=op.f("ck_memory_suppression_memory_suppression_fingerprint_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "source_derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_memory_suppression_vault_derived",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "source_verdict_id"],
            ["user_verdict.vault_id", "user_verdict.id"],
            name="fk_memory_suppression_vault_verdict",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_suppression")),
        sa.UniqueConstraint(
            "vault_id", "source_verdict_id", name="uq_memory_suppression_source_verdict"
        ),
    )
    op.create_index(
        op.f("ix_memory_suppression_normalized_fingerprint"),
        "memory_suppression",
        ["normalized_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_suppression_suppression_lineage_id"),
        "memory_suppression",
        ["suppression_lineage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_suppression_vault_id"), "memory_suppression", ["vault_id"], unique=False
    )
    op.create_table(
        "source_revision",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column(
            "content_ciphertext",
            sa.LargeBinary(),
            nullable=True,
            comment="Opaque application-produced ciphertext; never UTF-8 relabeled as encrypted",
        ),
        sa.Column("object_key", VaultObjectKeyType(length=1024), nullable=True),
        sa.Column("content_mime", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supersedes_revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "edit_origin",
            sa.Enum(
                "user",
                "import_replay",
                "transcription_correction",
                name="source_edit_origin",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "object_key IS NULL OR (object_key LIKE 'vaults/' || replace(lower(CAST(vault_id AS VARCHAR(36))), '-', '') || '/objects/%' AND object_key NOT LIKE '%/../%' AND object_key NOT LIKE '%/..' AND object_key NOT LIKE '%/./%' AND object_key NOT LIKE '%/.' AND object_key NOT LIKE '%//%' AND object_key NOT LIKE '%?%' AND object_key NOT LIKE '%#%')",
            name=op.f("ck_source_revision_source_revision_object_key_matches_vault"),
        ),
        sa.CheckConstraint(
            "content_ciphertext IS NOT NULL OR object_key IS NOT NULL",
            name=op.f("ck_source_revision_source_revision_has_storage"),
        ),
        sa.CheckConstraint(
            "revision_no >= 1", name=op.f("ck_source_revision_source_revision_no_positive")
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "document_id", "supersedes_revision_id"],
            ["source_revision.vault_id", "source_revision.document_id", "source_revision.id"],
            name="fk_source_revision_supersedes_same_document",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "document_id"],
            ["source_document.vault_id", "source_document.id"],
            name="fk_source_revision_vault_document",
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vault.id"], name="fk_source_revision_vault"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_revision")),
        sa.UniqueConstraint(
            "vault_id", "document_id", "id", name="uq_source_revision_vault_document_id_id"
        ),
        sa.UniqueConstraint(
            "vault_id",
            "document_id",
            "revision_no",
            name="uq_source_revision_vault_document_revision_no",
        ),
        sa.UniqueConstraint("vault_id", "id", name="uq_source_revision_vault_id_id"),
    )
    op.create_index(
        "ix_source_revision_vault_document",
        "source_revision",
        ["vault_id", "document_id", "revision_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_revision_vault_id"), "source_revision", ["vault_id"], unique=False
    )
    op.create_foreign_key(
        "fk_source_document_current_revision_same_document",
        "source_document",
        "source_revision",
        ["vault_id", "id", "current_revision_id"],
        ["vault_id", "document_id", "id"],
    )
    op.create_table(
        "source_fragment",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("audio_start_ms", sa.Integer(), nullable=True),
        sa.Column("audio_end_ms", sa.Integer(), nullable=True),
        sa.Column(
            "text_ciphertext",
            sa.LargeBinary(),
            nullable=False,
            comment="Opaque application-produced ciphertext; never plaintext masquerading as bytes",
        ),
        sa.Column("text_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "fragment_kind",
            sa.Enum(
                "paragraph",
                "utterance",
                "page",
                "caption",
                name="source_fragment_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(audio_start_ms IS NULL AND audio_end_ms IS NULL) OR (audio_start_ms IS NOT NULL AND audio_end_ms IS NOT NULL AND audio_start_ms >= 0 AND audio_end_ms >= audio_start_ms)",
            name=op.f("ck_source_fragment_source_fragment_valid_audio_range"),
        ),
        sa.CheckConstraint(
            "(char_start IS NULL AND char_end IS NULL) OR (char_start IS NOT NULL AND char_end IS NOT NULL AND char_start >= 0 AND char_end >= char_start)",
            name=op.f("ck_source_fragment_source_fragment_valid_char_range"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0", name=op.f("ck_source_fragment_source_fragment_ordinal_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "revision_id"],
            ["source_revision.vault_id", "source_revision.id"],
            name="fk_source_fragment_vault_revision",
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vault.id"], name="fk_source_fragment_vault"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_fragment")),
        sa.UniqueConstraint("vault_id", "id", name="uq_source_fragment_vault_id_id"),
        sa.UniqueConstraint(
            "vault_id", "revision_id", "ordinal", name="uq_source_fragment_vault_revision_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_source_fragment_vault_id"), "source_fragment", ["vault_id"], unique=False
    )
    op.create_table(
        "evidence_link",
        sa.Column("target_derived_object_id", sa.Uuid(), nullable=False),
        sa.Column("source_fragment_id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=False),
        sa.Column("source_revision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "supports",
                "contradicts",
                "contextualizes",
                name="evidence_relation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quote_start", sa.Integer(), nullable=False),
        sa.Column("quote_end", sa.Integer(), nullable=False),
        sa.Column("quote_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "extractor_reason",
            sa.Enum(
                "explicit_statement",
                "contradiction",
                "context",
                "user_correction",
                name="evidence_extraction_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "strength_band",
            sa.Enum(
                "weak",
                "moderate",
                "strong",
                name="evidence_strength",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("authorization_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_policy_epoch", sa.Integer(), nullable=False),
        sa.Column("source_generation", sa.Integer(), nullable=False),
        sa.Column("source_verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="evidence_source_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Enum(
                "knowledge_pipeline",
                "user",
                "source_reconciler",
                name="evidence_created_by",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="evidence_data_class",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "invalidated_reason",
            sa.Enum(
                "live",
                "tombstoned",
                "excluded",
                "consent_revoked",
                "stale",
                "unknown",
                name="evidence_invalidation_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(normalized_fingerprint) = 64",
            name=op.f("ck_evidence_link_evidence_link_normalized_fingerprint_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(quote_hash) = 64",
            name=op.f("ck_evidence_link_evidence_link_quote_hash_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(source_content_fingerprint) = 64",
            name=op.f("ck_evidence_link_evidence_link_source_fingerprint_sha256_length"),
        ),
        sa.CheckConstraint(
            "quote_start >= 0 AND quote_end > quote_start",
            name=op.f("ck_evidence_link_evidence_link_quote_interval_valid"),
        ),
        sa.CheckConstraint(
            "source_policy_epoch >= 0 AND source_generation >= 0",
            name=op.f("ck_evidence_link_evidence_link_source_fence_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "source_fragment_id"],
            ["source_fragment.vault_id", "source_fragment.id"],
            name="fk_evidence_link_vault_source_fragment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "target_derived_object_id"],
            ["derived_object.vault_id", "derived_object.id"],
            name="fk_evidence_link_vault_derived_object",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_link")),
        sa.UniqueConstraint(
            "vault_id",
            "target_derived_object_id",
            "source_fragment_id",
            "relation",
            "quote_hash",
            name="uq_evidence_link_anchor",
        ),
    )
    op.create_index(
        op.f("ix_evidence_link_normalized_fingerprint"),
        "evidence_link",
        ["normalized_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_link_source_fragment_id"),
        "evidence_link",
        ["source_fragment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_link_source_revision_id"),
        "evidence_link",
        ["source_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_link_target_derived_object_id"),
        "evidence_link",
        ["target_derived_object_id"],
        unique=False,
    )
    op.create_index(op.f("ix_evidence_link_vault_id"), "evidence_link", ["vault_id"], unique=False)
    op.create_table(
        "search_projection",
        sa.Column("source_fragment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "lexical_terms",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="Sensitive service-readable derived terms, not E2EE",
        ),
        sa.Column(
            "embedding",
            sa.JSON(none_as_null=True),
            nullable=True,
            comment="Sensitive service-readable derived vector, not E2EE",
        ),
        sa.Column("tokenizer_version", sa.String(length=128), nullable=True),
        sa.Column("embedding_version", sa.String(length=128), nullable=True),
        sa.Column("source_generation", sa.Integer(), nullable=False),
        sa.Column("policy_epoch", sa.Integer(), nullable=False),
        sa.Column("consent_record_id", sa.Uuid(), nullable=False),
        sa.Column(
            "index_policy",
            sa.Enum(
                "lexical",
                "semantic",
                "both",
                "none",
                name="search_index_policy",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vault_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum(
                "user",
                "system_component",
                "import",
                name="created_by",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "data_class",
            sa.Enum(
                "normal",
                "sensitive",
                "highly_sensitive",
                name="data_class",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "data_class <> 'highly_sensitive' OR (index_policy = 'none' AND lexical_terms IS NULL AND embedding IS NULL AND tokenizer_version IS NULL AND embedding_version IS NULL)",
            name=op.f("ck_search_projection_search_projection_highly_sensitive_no_index"),
        ),
        sa.CheckConstraint(
            "index_policy <> 'none' OR (lexical_terms IS NULL AND embedding IS NULL AND tokenizer_version IS NULL AND embedding_version IS NULL)",
            name=op.f("ck_search_projection_search_projection_none_has_no_payload"),
        ),
        sa.CheckConstraint(
            "policy_epoch > 0",
            name=op.f("ck_search_projection_search_projection_policy_epoch_positive"),
        ),
        sa.CheckConstraint(
            "source_generation >= 0",
            name=op.f("ck_search_projection_search_projection_generation_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "consent_record_id"],
            ["consent_record.vault_id", "consent_record.id"],
            name="fk_search_projection_vault_consent_record",
        ),
        sa.ForeignKeyConstraint(
            ["vault_id", "source_fragment_id"],
            ["source_fragment.vault_id", "source_fragment.id"],
            name="fk_search_projection_vault_fragment",
        ),
        sa.ForeignKeyConstraint(["vault_id"], ["vault.id"], name="fk_search_projection_vault"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_projection")),
        sa.UniqueConstraint("vault_id", "id", name="uq_search_projection_vault_id_id"),
        sa.UniqueConstraint(
            "vault_id", "source_fragment_id", name="uq_search_projection_vault_fragment"
        ),
    )
    op.create_index(
        op.f("ix_search_projection_vault_id"), "search_projection", ["vault_id"], unique=False
    )
    op.create_index(
        "ix_search_projection_vault_live",
        "search_projection",
        ["vault_id", "deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    load_model_registry()
    # Alembic revisions must not accidentally operate on tables introduced by
    # future model imports. Keep this revision's security snapshot explicit so a
    # fresh upgrade always creates a table before applying RLS to it.
    initial_table_names = {
        "claim_version",
        "consent_record",
        "derived_object",
        "evidence_link",
        "job",
        "memory_claim",
        "memory_suppression",
        "outbound_operation",
        "outbox_event",
        "search_projection",
        "source_document",
        "source_fragment",
        "source_revision",
        "user_verdict",
        "vault",
    }
    initial_metadata = sa.MetaData()
    # Do not sort current metadata here: later revisions may add a foreign key
    # from an initial table to a table that did not yet exist at this point.
    for table in Base.metadata.tables.values():
        if table.name in initial_table_names:
            table.to_metadata(initial_metadata)
    # Current ORM metadata may contain constraints introduced by later
    # revisions. Keep this historical security snapshot resolvable before the
    # model_run table exists; f3a6d8c2e901 adds these constraints explicitly.
    for table_name, constraint_name in (
        ("claim_version", "fk_claim_version_vault_model_run"),
        ("evidence_link", "fk_evidence_link_vault_model_run"),
        ("job", "fk_job_requested_by_principal"),
    ):
        copied = initial_metadata.tables[table_name]
        future_constraint = next(
            constraint for constraint in copied.constraints if constraint.name == constraint_name
        )
        for foreign_key in future_constraint.elements:
            foreign_key.parent.foreign_keys.discard(foreign_key)
            copied.foreign_keys.discard(foreign_key)
        copied.constraints.discard(future_constraint)
    apply_postgres_security(op.get_bind(), initial_metadata)


def downgrade() -> None:
    """Revert this revision."""
    op.execute('DROP SCHEMA IF EXISTS "life_coach_private" CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_projection_vault_live", table_name="search_projection")
    op.drop_index(op.f("ix_search_projection_vault_id"), table_name="search_projection")
    op.drop_table("search_projection")
    op.drop_index(op.f("ix_evidence_link_vault_id"), table_name="evidence_link")
    op.drop_index(op.f("ix_evidence_link_target_derived_object_id"), table_name="evidence_link")
    op.drop_index(op.f("ix_evidence_link_source_revision_id"), table_name="evidence_link")
    op.drop_index(op.f("ix_evidence_link_source_fragment_id"), table_name="evidence_link")
    op.drop_index(op.f("ix_evidence_link_normalized_fingerprint"), table_name="evidence_link")
    op.drop_table("evidence_link")
    op.drop_index(op.f("ix_source_fragment_vault_id"), table_name="source_fragment")
    op.drop_table("source_fragment")
    op.execute(
        'ALTER TABLE "source_document" DROP CONSTRAINT IF EXISTS '
        '"fk_source_document_current_revision_same_document"'
    )
    op.drop_index(op.f("ix_source_revision_vault_id"), table_name="source_revision")
    op.drop_index("ix_source_revision_vault_document", table_name="source_revision")
    op.drop_table("source_revision")
    op.drop_index(op.f("ix_memory_suppression_vault_id"), table_name="memory_suppression")
    op.drop_index(
        op.f("ix_memory_suppression_suppression_lineage_id"), table_name="memory_suppression"
    )
    op.drop_index(
        op.f("ix_memory_suppression_normalized_fingerprint"), table_name="memory_suppression"
    )
    op.drop_table("memory_suppression")
    op.drop_index("ix_consent_record_vault_purpose_source_epoch", table_name="consent_record")
    op.drop_index(op.f("ix_consent_record_vault_id"), table_name="consent_record")
    op.drop_table("consent_record")
    op.drop_index(op.f("ix_user_verdict_vault_id"), table_name="user_verdict")
    op.drop_index(op.f("ix_user_verdict_target_derived_object_id"), table_name="user_verdict")
    op.drop_index("ix_user_verdict_stream", table_name="user_verdict")
    op.drop_table("user_verdict")
    op.drop_index("ix_source_document_vault_live_created", table_name="source_document")
    op.drop_index(op.f("ix_source_document_vault_id"), table_name="source_document")
    op.drop_table("source_document")
    op.drop_index(
        "uq_job_outbox_event_type",
        table_name="job",
        postgresql_where=sa.text("outbox_event_id IS NOT NULL"),
        sqlite_where=sa.text("outbox_event_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_job_vault_id"), table_name="job")
    op.drop_index("ix_job_claimable", table_name="job")
    op.drop_table("job")
    op.drop_index(
        "uq_claim_version_current",
        table_name="claim_version",
        postgresql_where=sa.text("system_to IS NULL"),
        sqlite_where=sa.text("system_to IS NULL"),
    )
    op.drop_index(op.f("ix_claim_version_vault_id"), table_name="claim_version")
    op.drop_index(op.f("ix_claim_version_normalized_fingerprint"), table_name="claim_version")
    op.drop_index(op.f("ix_claim_version_claim_id"), table_name="claim_version")
    op.drop_index("ix_claim_version_bitemporal", table_name="claim_version")
    op.drop_table("claim_version")
    op.drop_index(op.f("ix_outbox_event_vault_id"), table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_outbound_operation_vault_id"), table_name="outbound_operation")
    op.drop_table("outbound_operation")
    op.drop_index(op.f("ix_memory_claim_vault_id"), table_name="memory_claim")
    op.drop_index(op.f("ix_memory_claim_suppression_lineage_id"), table_name="memory_claim")
    op.drop_table("memory_claim")
    op.drop_index(op.f("ix_derived_object_vault_id"), table_name="derived_object")
    op.drop_table("derived_object")
    op.drop_table("vault")
    # ### end Alembic commands ###
