import { useMemo, useState } from "react";
import { ArrowRight, BookOpenText, CalendarDays, Check, ChevronRight, Layers3, LoaderCircle, RefreshCw, Sparkles, Undo2 } from "lucide-react";
import { DateTimePicker, AppSelect } from "./Picker";
import type { BackendState, CalendarCandidate, MemoryInboxItem, NarrativeCitation, NarrativeGeneration, NarrativeProject } from "./types";
import "./NarrativeView.css";

type Props = {
  error: string | null; backend: BackendState; project: NarrativeProject | null;
  generations: NarrativeGeneration[]; calendarCandidates: CalendarCandidate[];
  memories: MemoryInboxItem[]; busy: string | null;
  onGenerate: (kind: "life_line" | "memoir_chapter") => void;
  onCreateCalendar: (generationId: string, payload: Pick<CalendarCandidate, "title" | "starts_at" | "ends_at" | "timezone" | "notes">) => void;
  onTransitionCalendar: (candidate: CalendarCandidate, target: "confirmed" | "revoked") => void;
  onDownloadCalendar: (candidate: CalendarCandidate) => void;
  onOpenMemory: (memoryId: string) => void;
  onReviewMemories: () => void; onApprovedMemories: () => void; onSettings: () => void; onRecords: () => void;
};
const dateLabel = (value: string) => new Date(value).toLocaleString("zh-CN", { month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" });
function tomorrow(minutes: number) { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(20, minutes, 0, 0); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function NarrativeView({ error, backend, generations, calendarCandidates, memories, busy, onGenerate, onCreateCalendar, onTransitionCalendar, onDownloadCalendar, onOpenMemory, onReviewMemories, onApprovedMemories, onSettings, onRecords }: Props) {
  const sorted = useMemo(() => [...generations].sort((a, b) => Date.parse(b.created_at) - Date.parse(a.created_at)), [generations]);
  const lines = sorted.filter(item => item.kind === "life_line");
  const chapter = sorted.find(item => item.kind === "memoir_chapter");
  const [selectedLineId, setSelectedLineId] = useState("");
  const line = lines.find(item => item.generation_id === selectedLineId) ?? lines[0];
  const approved = memories.filter(item => ["confirm", "correct"].includes(item.current_verdict || ""));
  const reviewed = approved.filter(item => item.version.state === "active" && item.support_count + item.counterevidence_count > 0);
  const pending = memories.filter(item => (!item.current_verdict || item.current_verdict === "snooze") && ["candidate", "active"].includes(item.version.state));
  const canGenerate = backend.capabilities.narratives && (backend.capabilities.narrative_generation ?? backend.capabilities.candidate_insights);
  const citations = line ? [...line.citations, ...line.themes.flatMap(theme => theme.citations)] : [];
  const citedIds = new Set(citations.map(item => item.memory_id));
  // Only compare known material versions; absence from a limited inbox is not evidence of deletion.
  const changed = citations.some(citation => memories.some(memory => memory.memory_id === citation.memory_id && (memory.version.derived_object_id !== citation.derived_object_id || !["confirm", "correct"].includes(memory.current_verdict || ""))));
  const notIncluded = reviewed.filter(item => !citedIds.has(item.memory_id));
  const [draft, setDraft] = useState(() => ({ title: "留半小时回看这一章", startsAt: tomorrow(0), endsAt: tomorrow(30), notes: "" }));
  const validDates = Boolean(draft.startsAt && draft.endsAt && Number.isFinite(Date.parse(draft.startsAt)) && Number.isFinite(Date.parse(draft.endsAt)) && Date.parse(draft.endsAt) > Date.parse(draft.startsAt));
  const saveCalendar = () => { if (!chapter || !validDates || !draft.title.trim()) return; onCreateCalendar(chapter.generation_id, { title: draft.title.trim(), starts_at: new Date(draft.startsAt).toISOString(), ends_at: new Date(draft.endsAt).toISOString(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "Asia/Shanghai", notes: draft.notes.trim() }); };
  const renderEvidence = (items: NarrativeCitation[]) => <div className="thread-evidence">{items.map((citation, index) => {
    const memory = memories.find(item => item.memory_id === citation.memory_id);
    return <button key={`${citation.memory_id}:${citation.relation}:${index}`} onClick={() => memory ? onOpenMemory(citation.memory_id) : onReviewMemories()}><span className="thread-evidence-kind">{citation.relation === "counterexample" ? "反例" : "依据"}</span><span>{memory?.version.derived_object_id === citation.derived_object_id ? memory.version.statement : memory ? "查看生成时引用的认识与原文" : "这条依据未在当前列表中，前往认识页查找"}</span><ChevronRight size={15} /></button>;
  })}</div>;
  return <div className="content-page narrative-page thread-page page-enter">
    <header className="thread-heading"><div><span className="thread-kicker">回看 · 连接 · 修正</span><h1>人生主线</h1><p>把已经认可的认识放在一起，看见重复出现的主题与例外。</p></div>{line && <button className="thread-button" disabled={busy !== null || !canGenerate || !reviewed.length} onClick={() => { setSelectedLineId(""); onGenerate("life_line"); }}>{busy === "narrative:life_line" ? <LoaderCircle className="spin" size={16} /> : <RefreshCw size={16} />}重新整理</button>}</header>
    {error && <p className="inline-notice" role="alert">{error}</p>}
    {busy === "load-narrative" && <p role="status"><LoaderCircle className="spin" size={16} /> 正在读取主线</p>}
    <section className="thread-status" aria-label="主线材料状态"><div><strong>{reviewed.length}</strong><span>可用于整理的认识</span></div><div><strong>{line?.themes.length ?? 0}</strong><span>当前版本的主题</span></div><div><strong>{pending.length}</strong><span>待你判断的认识</span></div><button onClick={onApprovedMemories}>查看材料 <ArrowRight size={15} /></button></section>
    {!line && <section className="thread-start"><div className="thread-start-icon"><Layers3 size={24} /></div><div><h2>{reviewed.length ? "已有材料，可以开始连接了" : "先选出一条你认可的认识"}</h2><p>{reviewed.length ? `当前列表中有 ${reviewed.length} 条你确认或纠正过的认识。整理后，这里会展示它们形成的主题、依据和另一种解释。` : pending.length ? `有 ${pending.length} 条认识还在等你判断。确认或纠正其中贴近你的内容，主线才有可信的起点。` : approved.length ? "已有认可的认识暂缺有效依据或已不是当前有效版本。先去认识页核对材料，再整理主线。" : "从一次具体经历开始记录，再到「认识」核对由它形成的理解。这里会逐步连接这些材料，而不是替你定义人生。"}</p><div className="thread-start-actions">{reviewed.length && canGenerate ? <button className="thread-button primary" disabled={busy !== null} onClick={() => onGenerate("life_line")}>{busy === "narrative:life_line" ? <LoaderCircle className="spin" size={16} /> : <Sparkles size={16} />}整理第一版主线</button> : <button className="thread-button primary" onClick={reviewed.length ? onSettings : pending.length ? onReviewMemories : approved.length ? onApprovedMemories : onRecords}>{reviewed.length ? "设置在线 AI" : pending.length || approved.length ? "去核对认识" : "记录一次经历"}<ArrowRight size={16} /></button>}<button className="thread-button" onClick={onApprovedMemories}>查看已认可的材料</button></div></div></section>}
    {!canGenerate && <div className="thread-notice"><span>{backend.phase === "offline" ? "连接暂不可用，恢复连接后可以整理主线。" : "叙事生成暂不可用，已有内容仍可回看。可到设置检查连接和在线 AI。"}</span><button onClick={onSettings}>查看设置 <ArrowRight size={14} /></button></div>}
    {line && <section className="thread-current"><div className="thread-section-heading"><div><span className="thread-kicker">当前阅读的版本 · {dateLabel(line.created_at)}</span><h2>{line.title || "这些经历之间的联系"}</h2></div>{lines.length > 1 && <AppSelect label="主线版本" value={line.generation_id} options={lines.map((item, index) => ({ value: item.generation_id, label: `${index === 0 ? "最新 · " : ""}第 ${lines.length - index} 版 · ${dateLabel(item.created_at)}` }))} onChange={setSelectedLineId} />}</div>
      {(changed || notIncluded.length > 0) && <p className="thread-change">{changed ? "部分关联认识已经更新，这一版仍保留生成时的理解。可以重新整理后再核对。" : `当前还有 ${notIncluded.length} 条已认可认识未被这一版引用；需要时可重新整理。`}</p>}
      <p className="thread-overview">{line.body}</p><div className="thread-themes">{line.themes.map((theme, index) => <article className="thread-theme" key={theme.theme_id}><div className="thread-theme-title"><span>{String(index + 1).padStart(2, "0")}</span><h3>{theme.title}</h3></div><p>{theme.interpretation}</p>{renderEvidence(theme.citations)}<div className="thread-limits"><div><strong>另一种解释</strong><p>{theme.counterpoint || "这一版没有提供其他解释。"}</p></div><div><strong>还缺少什么</strong><p>{theme.uncovered_period || "这一版未标明材料空白。"}</p></div></div></article>)}</div>{line.uncertainty && <p className="thread-footnote">{line.uncertainty}</p>}<div className="thread-next"><div><strong>下一次回看，可以从这里开始</strong><p>点开一条依据，看看它现在还贴不贴近你；不准确的地方可以在认识中重新判断。</p></div><button className="thread-button" onClick={onApprovedMemories}>核对与修正 <ArrowRight size={16} /></button></div>
    </section>}
    {reviewed.length > 0 && <details className="thread-materials" open={!line}><summary>已认可的材料 <span>{reviewed.length} 条 · 点击可查看依据或更新判断</span></summary><div>{reviewed.map(item => <button key={item.memory_id} onClick={() => onOpenMemory(item.memory_id)}><span>{item.version.statement}</span><small>{item.current_verdict === "correct" ? "已纠正" : "已确认"} · {item.support_count} 条支持线索</small><ChevronRight size={16} /></button>)}</div></details>}
    <section className="thread-chapter"><div className="thread-section-heading"><div><h2><BookOpenText size={20} /> 写成一章</h2><p>想把这些经历保留下来时，再整理成回忆录草稿。</p></div><button className="thread-button" disabled={busy !== null || !canGenerate || !reviewed.length} onClick={() => onGenerate("memoir_chapter")}>{busy === "narrative:memoir_chapter" ? <LoaderCircle className="spin" size={16} /> : <BookOpenText size={16} />}{chapter ? "生成新的章节" : "写一章回忆录"}</button></div>{chapter && <details className="thread-chapter-body"><summary>{chapter.title}<span>AI 草稿 · {dateLabel(chapter.created_at)}</span></summary>{chapter.body.split("\n").filter(Boolean).map((text, index) => <p key={index}>{text}</p>)}{renderEvidence(chapter.citations)}{chapter.uncertainty && <p className="thread-footnote">{chapter.uncertainty}</p>}</details>}</section>
    {chapter && <details className="thread-calendar"><summary><CalendarDays size={18} /> 安排一次回看 <span>可选 · 确认后下载日历文件</span></summary>{backend.capabilities.calendar_candidates ? <div className="calendar-draft"><label><span>标题</span><input value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></label><div><label><span>开始</span><DateTimePicker label="开始" value={draft.startsAt} onChange={value => setDraft({ ...draft, startsAt: value })} /></label><label><span>结束</span><DateTimePicker label="结束" value={draft.endsAt} onChange={value => setDraft({ ...draft, endsAt: value })} /></label></div>{!validDates && <p role="alert">结束时间需要晚于开始时间。</p>}<label><span>备注（可留空）</span><input value={draft.notes} onChange={event => setDraft({ ...draft, notes: event.target.value })} /></label><button className="thread-button" disabled={busy !== null || !validDates || !draft.title.trim()} onClick={saveCalendar}>保存为待确认事项</button></div> : <p>日历功能暂不可用。</p>}{calendarCandidates.map(candidate => <article className="thread-calendar-item" key={candidate.candidate_id}><div><strong>{candidate.title}</strong><p>{dateLabel(candidate.starts_at)} — {dateLabel(candidate.ends_at)}</p><small>{candidate.state === "proposed" ? "待确认" : candidate.state === "confirmed" ? "已确认" : "已撤销"}</small></div>{candidate.state !== "revoked" && <div><button className="thread-button" disabled={busy !== null} onClick={() => candidate.state === "confirmed" ? onDownloadCalendar(candidate) : onTransitionCalendar(candidate, "confirmed")}><Check size={15} />{candidate.state === "confirmed" ? "下载 .ics" : "确认"}</button><button className="thread-button" disabled={busy !== null} onClick={() => onTransitionCalendar(candidate, "revoked")}><Undo2 size={15} />撤销</button></div>}</article>)}</details>}
  </div>;
}
