"""PostgreSQL jobs, outbox, and outbound-operation execution fences."""

from life_coach.jobs.contracts import (
    AuthoritativeFenceReader,
    DispatchLease,
    ExactOutboundAuthorization,
    ExactOutboundAuthorizationPort,
    FenceSnapshot,
    IdempotencyConflict,
    JobExecutionContext,
    JobSpec,
    LeaseLostError,
    OutboundAuthorizationRejected,
    OutboundExecutionGuardError,
    OutboundExecutionTicket,
    OutboundOperationSpec,
    OutboundReconciliationTicket,
    OutboxEventSpec,
    StagedOutboundExecution,
)
from life_coach.jobs.enums import (
    CompletionStatus,
    FailureClass,
    FenceCheckpoint,
    JobQueue,
    JobState,
    OutboundAuthorizationDecision,
    OutboundOperationState,
)
from life_coach.jobs.models import Job, OutboundOperation, OutboxEvent
from life_coach.jobs.repository import (
    GlobalDispatcherRepository,
    OutboundOperationRepository,
    VaultJobRepository,
    VaultProcessorRepository,
)

__all__ = [
    "AuthoritativeFenceReader",
    "CompletionStatus",
    "DispatchLease",
    "ExactOutboundAuthorization",
    "ExactOutboundAuthorizationPort",
    "FailureClass",
    "FenceCheckpoint",
    "FenceSnapshot",
    "GlobalDispatcherRepository",
    "IdempotencyConflict",
    "Job",
    "JobExecutionContext",
    "JobQueue",
    "JobSpec",
    "JobState",
    "LeaseLostError",
    "OutboundAuthorizationDecision",
    "OutboundAuthorizationRejected",
    "OutboundExecutionGuardError",
    "OutboundExecutionTicket",
    "OutboundOperation",
    "OutboundOperationRepository",
    "OutboundOperationSpec",
    "OutboundOperationState",
    "OutboundReconciliationTicket",
    "OutboxEvent",
    "OutboxEventSpec",
    "StagedOutboundExecution",
    "VaultJobRepository",
    "VaultProcessorRepository",
]
