"""Source Vault models and transaction-neutral synchronous services."""

from .contracts import (
    DeletionSink,
    DeletionStep,
    DeletionStepState,
    SourceDeletionPlan,
    SourceReadResult,
    SourceWriteResult,
)
from .exceptions import (
    ImmutableRevisionError,
    InvalidSourceData,
    RevisionConflict,
    SourceDeleted,
    SourceError,
    SourceNotFound,
)
from .models import (
    EditOrigin,
    FragmentKind,
    IndexPolicy,
    ProcessingState,
    SearchProjection,
    SourceDocument,
    SourceFragment,
    SourceOrigin,
    SourceRevision,
    SourceType,
)
from .service import (
    DELETION_SINKS,
    SourceService,
    append_source_revision,
    build_source_deletion_plan,
    create_search_projection,
    create_source_document,
    create_source_fragment,
    get_source_document,
    get_source_revision,
    list_source_documents,
    read_source_document,
    tombstone_source_document,
)

__all__ = [
    "DELETION_SINKS",
    "DeletionSink",
    "DeletionStep",
    "DeletionStepState",
    "EditOrigin",
    "FragmentKind",
    "ImmutableRevisionError",
    "IndexPolicy",
    "InvalidSourceData",
    "ProcessingState",
    "RevisionConflict",
    "SearchProjection",
    "SourceDeleted",
    "SourceDeletionPlan",
    "SourceDocument",
    "SourceError",
    "SourceFragment",
    "SourceNotFound",
    "SourceOrigin",
    "SourceReadResult",
    "SourceRevision",
    "SourceService",
    "SourceType",
    "SourceWriteResult",
    "append_source_revision",
    "build_source_deletion_plan",
    "create_search_projection",
    "create_source_document",
    "create_source_fragment",
    "get_source_document",
    "get_source_revision",
    "list_source_documents",
    "read_source_document",
    "tombstone_source_document",
]
